/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2015-10-12 01:58:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class base_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/jsp_layout.tld", Long.valueOf(1443426900023L));
    _jspx_dependants.put("jar:file:/D:/MyCodes/Java/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DuoMeiTi/WEB-INF/lib/struts2-core-2.3.24.jar!/META-INF/struts-tags.tld", Long.valueOf(1430627084000L));
    _jspx_dependants.put("/jsp/base/base.jsp", Long.valueOf(1444445454630L));
    _jspx_dependants.put("/jsp/base/taglib.jsp", Long.valueOf(1443426900665L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.3.24.jar", Long.valueOf(1443426900605L));
    _jspx_dependants.put("/WEB-INF/pagetag.tld", Long.valueOf(1443426900613L));
    _jspx_dependants.put("/jsp/base/user_base.jsp", Long.valueOf(1444445454630L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005felse;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005felse = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname.release();
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fs_005felse.release();
    _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005foverride_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005foverride_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("    \t\r\n");
      out.write("    \t");
      if (_jspx_meth_layout_005fblock_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        <meta charset=\"utf-8\"/>\r\n");
      out.write("        <meta name=\"renderer\" content=\"webkit\"/>\r\n");
      out.write("        <title>多媒体管理系统</title>\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("        <meta name=\"keywords\" content=\"\" />\r\n");
      out.write("        <meta name=\"author\" content=\"\" />\r\n");
      out.write("\t\t<script type='text/javascript' src=\"/js/base/myutil.js\"></script>\r\n");
      out.write("        <link href=\"/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t\t<link href=\"/bootstrap/css/bootstrap-theme.min.css\" rel=\"stylesheet\" />\t\t\r\n");
      out.write("\t\t<link href=\"/datepicker/css/bootstrap-datetimepicker.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("        <script type='text/javascript' src=\"/js/base/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("        <script type='text/javascript' src=\"/datepicker/js/bootstrap-datetimepicker.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/datepicker/js/bootstrap-datetimepicker.zh-CN.js\" charset=\"UTF-8\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"/css/base/table.css\" >\t\t\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"/css/base/base.css\"/> \r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"/css/admin/classroom_manage.css\"/>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"/css/admin/repertory.css\"/>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"/css/base/websocket.css\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      if (_jspx_meth_layout_005fblock_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </head>   \r\n");
      out.write("\r\n");
      out.write("    <body >\r\n");
      out.write("\t\t<div id=\"basecontent\">\t\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_layout_005fblock_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    \t</div>\r\n");
      out.write("\t\t<footer class=\"container\" style=\"text-align:center\">\r\n");
      out.write("\t\t  <p>Copyright © 1986 - 2016 All rights reserved | <a href=\"http://chuangxin.dlut.edu.cn\">大连理工大学创新实验学院版权所有</a> | GPLv3 <a href=\"http://gplv3.fsf.org/\">Terms</a></p>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("        <script type='text/javascript' src=\"/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!--TinyMCE Editor-->\r\n");
      out.write("\t\t<script type='text/javascript' src=\"/js/base/tiny_mce.js\"></script>\r\n");
      out.write("\t\t<!-- JQuery Masonry-->\r\n");
      out.write("\t\t<script type='text/javascript' src=\"/js/base/jquery.masonry.min.js\"></script>\r\n");
      out.write("\t\t<script type='text/javascript' src=\"/js/base/base.js\"></script>\t\t       \r\n");
      out.write("        <!-- 百度推广JS -->\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("            var _bdhmProtocol = ((\"https:\" == document.location.protocol) ? \" https://\" : \" http://\");\r\n");
      out.write("        </script>\r\n");
      out.write("         <!-- 百度推广JS END -->\r\n");
      out.write("        </body>\r\n");
      out.write("    </html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \t");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005foverride_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:override
    tags.OverrideTag _jspx_th_layout_005foverride_005f0 = (tags.OverrideTag) _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname.get(tags.OverrideTag.class);
    _jspx_th_layout_005foverride_005f0.setPageContext(_jspx_page_context);
    _jspx_th_layout_005foverride_005f0.setParent(null);
    // /jsp/admin/base.jsp(5,0) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_layout_005foverride_005f0.setName("menu_list");
    int _jspx_eval_layout_005foverride_005f0 = _jspx_th_layout_005foverride_005f0.doStartTag();
    if (_jspx_eval_layout_005foverride_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_layout_005foverride_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_layout_005foverride_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_layout_005foverride_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("\r\n");
        out.write("\t<div class=\"menu-list\">\r\n");
        out.write("\t    <a href=\"/admin/classroom/\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-blackboard\">&nbsp;教室管理</span></a>\r\n");
        out.write("\t    <a href=\"/admin/repertory\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-th-large\">&nbsp;设备管理</span></a>\r\n");
        out.write("\t    <a href=\"/admin/classroomDevice/maintainRecords\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-th\">&nbsp;维修记录管理</span></a>\r\n");
        out.write("\t    <a href=\"/admin/student_manage/\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-list-alt\">&nbsp;在职学生管理</span></a>\r\n");
        out.write("\t    <a href=\"/admin/user_request/\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-list-alt\">&nbsp;用户注册请求</span></a>\r\n");
        out.write("\t    \r\n");
        out.write("\t    <a href=\"/admin/usefdsaf\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-list-alt\">&nbsp;账号生成</span></a>\r\n");
        out.write("\r\n");
        out.write("<!-- \t    <a href=\"/admin/wer\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-list-alt\">&nbsp;主页修改</span></a> -->\r\n");
        out.write("<!-- \t    <a href=\"/admin/notice\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-list-alt\">&nbsp;公告管理</span></a> -->\r\n");
        out.write("\r\n");
        out.write("\t    <a href=\"/admin/HomepageModify/\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-list-alt\">&nbsp;主页修改</span></a>\r\n");
        out.write("\t    <a href=\"/admin/adf\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-list-alt\">&nbsp;日志管理</span></a>\r\n");
        out.write("\t    <a href=\"/admin/asdf\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-list-alt\">&nbsp;远程控制</span></a>\r\n");
        out.write("\t    <a href=\"/admin/modifypassword\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-lock\">&nbsp;修改密码</span></a>\r\n");
        out.write("\t    <a href=\"/admin/user_information\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-list-alt\">&nbsp;个人信息</span></a>\r\n");
        out.write("\t    <a href=\"/logout\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-list-alt\">&nbsp;安全退出</span></a>\r\n");
        out.write("\t    <div class=\"menu-blank\"></div>\r\n");
        out.write("\t</div>\r\n");
        out.write("\t\r\n");
        out.write("\t \r\n");
        out.write(" ");
        int evalDoAfterBody = _jspx_th_layout_005foverride_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_layout_005foverride_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_layout_005foverride_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname.reuse(_jspx_th_layout_005foverride_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname.reuse(_jspx_th_layout_005foverride_005f0);
    return false;
  }

  private boolean _jspx_meth_layout_005foverride_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:override
    tags.OverrideTag _jspx_th_layout_005foverride_005f1 = (tags.OverrideTag) _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname.get(tags.OverrideTag.class);
    _jspx_th_layout_005foverride_005f1.setPageContext(_jspx_page_context);
    _jspx_th_layout_005foverride_005f1.setParent(null);
    // /jsp/base/user_base.jsp(3,0) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_layout_005foverride_005f1.setName("base_content");
    int _jspx_eval_layout_005foverride_005f1 = _jspx_th_layout_005foverride_005f1.doStartTag();
    if (_jspx_eval_layout_005foverride_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_layout_005foverride_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_layout_005foverride_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_layout_005foverride_005f1.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("\t\r\n");
        out.write("<a href=\"/\">\r\n");
        out.write("    <div id=\"headerpic\" >\r\n");
        out.write("        <ul class=\"nav navbar-right\">\r\n");
        out.write("            <li id=\"welcome_word\">\r\n");
        out.write("            \t欢迎您: <span id=\"login_user_name\">");
        if (_jspx_meth_s_005fproperty_005f0(_jspx_th_layout_005foverride_005f1, _jspx_page_context))
          return true;
        out.write("</span>\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("<!--             \t<p></p> -->\r\n");
        out.write("            \t\r\n");
        out.write("            \t");
        if (_jspx_meth_s_005fif_005f0(_jspx_th_layout_005foverride_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("            \t");
        if (_jspx_meth_s_005felse_005f0(_jspx_th_layout_005foverride_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("            \t\r\n");
        out.write("            \t\r\n");
        out.write("            </li>\r\n");
        out.write("        </ul>\r\n");
        out.write("    </div>\r\n");
        out.write("</a>\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("<div class=\"container-fluid main-container\">\r\n");
        out.write("    <div class=\"row col-lg-12\">\r\n");
        out.write("        <div class=\"col-lg-3 \">\t                    \r\n");
        out.write("            ");
        if (_jspx_meth_layout_005fblock_005f0(_jspx_th_layout_005foverride_005f1, _jspx_page_context))
          return true;
        out.write("\t\r\n");
        out.write("        </div>\r\n");
        out.write("        <div class=\"col-lg-9\">\r\n");
        out.write("        \t<div class=\"main-content\">\r\n");
        out.write("            \t");
        if (_jspx_meth_layout_005fblock_005f1(_jspx_th_layout_005foverride_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("         </div>\r\n");
        out.write("        </div>\r\n");
        out.write("    </div>\r\n");
        out.write("</div>\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("<!-- \r\n");
        out.write("<div id=\"envelope\"></div>\r\n");
        out.write("<div id=\"message-list-box\" class=\"hide\">\r\n");
        out.write("\t<div class=\"message-list-top\">\r\n");
        out.write("\t\t<span class=\"title\">消息</span>\r\n");
        out.write("\t\t<span class=\"glyphicon glyphicon-remove closed\"></span>\r\n");
        out.write("\t\t<span class=\"glyphicon glyphicon-user users\"></span>\r\n");
        out.write("\t</div>\r\n");
        out.write("\t<div class=\"message-list\"></div>\r\n");
        out.write("\t<div class=\"message-list-bottom\" id=\"write-message\">\r\n");
        out.write("\t\t<span>发信息</span>\r\n");
        out.write("\t</div>\r\n");
        out.write("</div>\r\n");
        out.write("\r\n");
        out.write("<div id=\"message-contacts-box\" class=\"hide\">\r\n");
        out.write("\t<div class=\"message-contacts-top\">\r\n");
        out.write("\t\t<span class=\"title\">联系人</span>\r\n");
        out.write("\t\t<span class=\"glyphicon glyphicon-remove closed\"></span>\r\n");
        out.write("\t</div>\r\n");
        out.write("\t<div class=\"message-contacts\">\r\n");
        out.write("    \t<h4>\r\n");
        out.write("        \t<a class=\"contacts-expand collapsed\" data-toggle=\"collapse\" href=\"#admin-contacts\" aria-expanded=\"false\" aria-controls=\"admin-contacts\">\r\n");
        out.write("          \t\t<span class=\"glyphicon glyphicon-plus\"></span>  管理员\r\n");
        out.write("        \t</a>\r\n");
        out.write("      \t</h4>\r\n");
        out.write("    \t<div id=\"admin-contacts\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingOne\">\r\n");
        out.write("      \t\t<ul class=\"contacts-list-group list-group\"></ul>\r\n");
        out.write("    \t</div>\r\n");
        out.write("\t    <h4>\r\n");
        out.write("\t        <a class=\"contacts-expand collapsed\" data-toggle=\"collapse\" href=\"#teacher-contacts\" aria-expanded=\"false\" aria-controls=\"teacher-contacts\">\r\n");
        out.write("\t          \t<span class=\"glyphicon glyphicon-plus\"></span>  教师\r\n");
        out.write("\t        </a>\r\n");
        out.write("\t    </h4>\r\n");
        out.write("\t    <div id=\"teacher-contacts\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingTwo\">\r\n");
        out.write("\t      \t<ul class=\"contacts-list-group list-group\"></ul>\r\n");
        out.write("\t    </div>\r\n");
        out.write("\t    <h4>\r\n");
        out.write("\t        <a class=\"contacts-expand collapsed\" data-toggle=\"collapse\" href=\"#student-contacts\" aria-expanded=\"false\" aria-controls=\"student-contacts\">\r\n");
        out.write("\t          \t<span class=\"glyphicon glyphicon-plus\"></span>  学生\r\n");
        out.write("\t        </a>\r\n");
        out.write("\t    </h4>\r\n");
        out.write("\t    <div id=\"student-contacts\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingTwo\">\r\n");
        out.write("\t      \t<ul class=\"contacts-list-group list-group\"></ul>\r\n");
        out.write("\t    </div>\r\n");
        out.write("\t</div>\r\n");
        out.write("</div>\r\n");
        out.write("\r\n");
        out.write("<div id=\"message-content-box\" class=\"hide\" from=");
        if (_jspx_meth_s_005fproperty_005f1(_jspx_th_layout_005foverride_005f1, _jspx_page_context))
          return true;
        out.write(">\r\n");
        out.write("\t<div class=\"message-content-top\">\r\n");
        out.write("\t\t<span class=\"title\">某某某</span>\r\n");
        out.write("\t\t<span class=\"glyphicon glyphicon-remove closed\"></span>\r\n");
        out.write("\t\t<span class=\"glyphicon glyphicon-user users\"></span>\r\n");
        out.write("\t\t<span class=\"glyphicon glyphicon-menu-left back\"></span>\r\n");
        out.write("\t</div>\r\n");
        out.write("\t<div class=\"message-content\"></div>\r\n");
        out.write("\t<div class=\"message-tool\"></div>\r\n");
        out.write("\t<div class=\"message-writeboard\">\r\n");
        out.write("\t\t<textarea class=\"form-control\" rows=\"4\"></textarea>\r\n");
        out.write("\t\t<div class=\"send-bottom\">\r\n");
        out.write("\t\t\t<button type=\"button\" class=\"btn btn-sm\" onclick=\"sendMessage()\">发送</button>\r\n");
        out.write("\t\t</div>\r\n");
        out.write("\t</div>\r\n");
        out.write("</div>\r\n");
        out.write("\r\n");
        out.write("<script type=\"text/javascript\" src=\"/js/base/websocket.js\"></script>\r\n");
        out.write(" -->\r\n");
        out.write("        \r\n");
        out.write(" ");
        if (_jspx_meth_layout_005fblock_005f2(_jspx_th_layout_005foverride_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\r\n");
        out.write("\r\n");
        out.write("\t\r\n");
        out.write("\t\r\n");
        int evalDoAfterBody = _jspx_th_layout_005foverride_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_layout_005foverride_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_layout_005foverride_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname.reuse(_jspx_th_layout_005foverride_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname.reuse(_jspx_th_layout_005foverride_005f1);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_layout_005foverride_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f0 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_layout_005foverride_005f1);
    // /jsp/base/user_base.jsp(9,45) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f0.setValue("#session.username");
    int _jspx_eval_s_005fproperty_005f0 = _jspx_th_s_005fproperty_005f0.doStartTag();
    if (_jspx_th_s_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_layout_005foverride_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:if
    org.apache.struts2.views.jsp.IfTag _jspx_th_s_005fif_005f0 = (org.apache.struts2.views.jsp.IfTag) _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.get(org.apache.struts2.views.jsp.IfTag.class);
    _jspx_th_s_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_layout_005foverride_005f1);
    // /jsp/base/user_base.jsp(14,13) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fif_005f0.setTest("#session.role.equals(@util.Const@AdminRole)");
    int _jspx_eval_s_005fif_005f0 = _jspx_th_s_005fif_005f0.doStartTag();
    if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fif_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fif_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("            \t\t(您是管理员)\r\n");
        out.write("            \t");
        int evalDoAfterBody = _jspx_th_s_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005felse_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_layout_005foverride_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:else
    org.apache.struts2.views.jsp.ElseTag _jspx_th_s_005felse_005f0 = (org.apache.struts2.views.jsp.ElseTag) _005fjspx_005ftagPool_005fs_005felse.get(org.apache.struts2.views.jsp.ElseTag.class);
    _jspx_th_s_005felse_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005felse_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_layout_005foverride_005f1);
    int _jspx_eval_s_005felse_005f0 = _jspx_th_s_005felse_005f0.doStartTag();
    if (_jspx_eval_s_005felse_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005felse_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005felse_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005felse_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("            \t\t(您是在职学生)\r\n");
        out.write("            \t");
        int evalDoAfterBody = _jspx_th_s_005felse_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005felse_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005felse_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005felse.reuse(_jspx_th_s_005felse_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005felse.reuse(_jspx_th_s_005felse_005f0);
    return false;
  }

  private boolean _jspx_meth_layout_005fblock_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_layout_005foverride_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:block
    tags.BlockTag _jspx_th_layout_005fblock_005f0 = (tags.BlockTag) _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.get(tags.BlockTag.class);
    _jspx_th_layout_005fblock_005f0.setPageContext(_jspx_page_context);
    _jspx_th_layout_005fblock_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_layout_005foverride_005f1);
    // /jsp/base/user_base.jsp(33,12) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_layout_005fblock_005f0.setName("menu_list");
    int _jspx_eval_layout_005fblock_005f0 = _jspx_th_layout_005fblock_005f0.doStartTag();
    if (_jspx_eval_layout_005fblock_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("            ");
        int evalDoAfterBody = _jspx_th_layout_005fblock_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_layout_005fblock_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f0);
    return false;
  }

  private boolean _jspx_meth_layout_005fblock_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_layout_005foverride_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:block
    tags.BlockTag _jspx_th_layout_005fblock_005f1 = (tags.BlockTag) _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.get(tags.BlockTag.class);
    _jspx_th_layout_005fblock_005f1.setPageContext(_jspx_page_context);
    _jspx_th_layout_005fblock_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_layout_005foverride_005f1);
    // /jsp/base/user_base.jsp(38,13) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_layout_005fblock_005f1.setName("main_content");
    int _jspx_eval_layout_005fblock_005f1 = _jspx_th_layout_005fblock_005f1.doStartTag();
    if (_jspx_eval_layout_005fblock_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("            \t");
        int evalDoAfterBody = _jspx_th_layout_005fblock_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_layout_005fblock_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f1);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_layout_005foverride_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f1 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_layout_005foverride_005f1);
    // /jsp/base/user_base.jsp(93,48) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f1.setValue("#session.user_id");
    int _jspx_eval_s_005fproperty_005f1 = _jspx_th_s_005fproperty_005f1.doStartTag();
    if (_jspx_th_s_005fproperty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f1);
    return false;
  }

  private boolean _jspx_meth_layout_005fblock_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_layout_005foverride_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:block
    tags.BlockTag _jspx_th_layout_005fblock_005f2 = (tags.BlockTag) _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.get(tags.BlockTag.class);
    _jspx_th_layout_005fblock_005f2.setPageContext(_jspx_page_context);
    _jspx_th_layout_005fblock_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_layout_005foverride_005f1);
    // /jsp/base/user_base.jsp(113,1) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_layout_005fblock_005f2.setName("nav_content");
    int _jspx_eval_layout_005fblock_005f2 = _jspx_th_layout_005fblock_005f2.doStartTag();
    if (_jspx_eval_layout_005fblock_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write(" \r\n");
        out.write(" ");
        int evalDoAfterBody = _jspx_th_layout_005fblock_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_layout_005fblock_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f2);
    return false;
  }

  private boolean _jspx_meth_layout_005fblock_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:block
    tags.BlockTag _jspx_th_layout_005fblock_005f3 = (tags.BlockTag) _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.get(tags.BlockTag.class);
    _jspx_th_layout_005fblock_005f3.setPageContext(_jspx_page_context);
    _jspx_th_layout_005fblock_005f3.setParent(null);
    // /jsp/base/base.jsp(12,5) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_layout_005fblock_005f3.setName("head_begin");
    int _jspx_eval_layout_005fblock_005f3 = _jspx_th_layout_005fblock_005f3.doStartTag();
    if (_jspx_eval_layout_005fblock_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("    \t");
        int evalDoAfterBody = _jspx_th_layout_005fblock_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_layout_005fblock_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f3);
    return false;
  }

  private boolean _jspx_meth_layout_005fblock_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:block
    tags.BlockTag _jspx_th_layout_005fblock_005f4 = (tags.BlockTag) _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.get(tags.BlockTag.class);
    _jspx_th_layout_005fblock_005f4.setPageContext(_jspx_page_context);
    _jspx_th_layout_005fblock_005f4.setParent(null);
    // /jsp/base/base.jsp(37,2) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_layout_005fblock_005f4.setName("head_end");
    int _jspx_eval_layout_005fblock_005f4 = _jspx_th_layout_005fblock_005f4.doStartTag();
    if (_jspx_eval_layout_005fblock_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\r\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_layout_005fblock_005f4.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_layout_005fblock_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f4);
    return false;
  }

  private boolean _jspx_meth_layout_005fblock_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:block
    tags.BlockTag _jspx_th_layout_005fblock_005f5 = (tags.BlockTag) _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.get(tags.BlockTag.class);
    _jspx_th_layout_005fblock_005f5.setPageContext(_jspx_page_context);
    _jspx_th_layout_005fblock_005f5.setParent(null);
    // /jsp/base/base.jsp(44,3) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_layout_005fblock_005f5.setName("base_content");
    int _jspx_eval_layout_005fblock_005f5 = _jspx_th_layout_005fblock_005f5.doStartTag();
    if (_jspx_eval_layout_005fblock_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_layout_005fblock_005f5.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_layout_005fblock_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f5);
    return false;
  }
}
