/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2015-10-12 05:21:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import model.Classroom;

public final class maintainRecords_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/WEB-INF/jsp_layout.tld", Long.valueOf(1443426900023L));
    _jspx_dependants.put("/jsp/admin/base.jsp", Long.valueOf(1444351303707L));
    _jspx_dependants.put("jar:file:/D:/MyCodes/Java/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DuoMeiTi/WEB-INF/lib/struts2-core-2.3.24.jar!/META-INF/struts-tags.tld", Long.valueOf(1430627084000L));
    _jspx_dependants.put("/jsp/base/base.jsp", Long.valueOf(1444616707352L));
    _jspx_dependants.put("/jsp/base/taglib.jsp", Long.valueOf(1443426900665L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.3.24.jar", Long.valueOf(1443426900605L));
    _jspx_dependants.put("/WEB-INF/pagetag.tld", Long.valueOf(1443426900613L));
    _jspx_dependants.put("/jsp/base/user_base.jsp", Long.valueOf(1444445454630L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("model.Classroom");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005felse;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005felse = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname.release();
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fs_005felse.release();
    _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write('\r');
      out.write('\n');
      //  layout:override
      tags.OverrideTag _jspx_th_layout_005foverride_005f0 = (tags.OverrideTag) _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname.get(tags.OverrideTag.class);
      _jspx_th_layout_005foverride_005f0.setPageContext(_jspx_page_context);
      _jspx_th_layout_005foverride_005f0.setParent(null);
      // /jsp/admin/maintainRecords.jsp(7,0) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005foverride_005f0.setName("main_content");
      int _jspx_eval_layout_005foverride_005f0 = _jspx_th_layout_005foverride_005f0.doStartTag();
      if (_jspx_eval_layout_005foverride_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_layout_005foverride_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.pushBody();
          _jspx_th_layout_005foverride_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
          _jspx_th_layout_005foverride_005f0.doInitBody();
        }
        do {
          out.write("\r\n");
          out.write("<style>\r\n");
          out.write("td,tr,th{\r\n");
          out.write("\ttext-align:center;\r\n");
          out.write("\tvertical-align:middle;\r\n");
          out.write("}\r\n");
          out.write("</style>\r\n");
          out.write("\r\n");
          out.write("\t<div class=\"mycontent\">\r\n");
          out.write("\t\t<!--  <div class=\"row\">\r\n");
          out.write("\t\t\t<label type=\"label\" class=\"btn btn-primary\"\r\n");
          out.write("\t\t\t\tstyle=\"width: 100%; float: left\">设备维修记录</label>\r\n");
          out.write("\t\t</div>-->\r\n");
          out.write("\t\t<hr>\r\n");
          out.write("\r\n");
          out.write("\t\t<div class=\"radios\">\r\n");
          out.write("\t\t\t<label class=\"radio-inline\" style=\"margin-left:5%\" > <input type=\"radio\"\r\n");
          out.write("\t\t\t\tname=\"radio-select\" value=\"0\"\r\n");
          out.write("\t\t\t\tonclick=\"return showdiv('#buildingCondition')\" checked> 按教学楼\r\n");
          out.write("\t\t\t</label> <!-- <label class=\"radio-inline\" style=\"margin-left:5%\" > <input type=\"radio\"\r\n");
          out.write("\t\t\t\tname=\"radio-select\" value=\"1\"\r\n");
          out.write("\t\t\t\tonclick=\"return showdiv('#buildingCondition')\"> 按教学楼\r\n");
          out.write("\t\t\t</label>  --><label class=\"radio-inline\" style=\"margin-left:5%\" > <input type=\"radio\"\r\n");
          out.write("\t\t\t\tname=\"radio-select\" value=\"2\"\r\n");
          out.write("\t\t\t\tonclick=\"return showdiv('#equipmentCondition')\"> 按设备\r\n");
          out.write("\t\t\t</label> <label class=\"radio-inline\" style=\"margin-left:5%\" > <input type=\"radio\"\r\n");
          out.write("\t\t\t\tname=\"radio-select\" value=\"3\"\r\n");
          out.write("\t\t\t\tonclick=\"return showdiv('#timeCondition')\"> 按时间\r\n");
          out.write("\t\t\t</label>\r\n");
          out.write("\t\t\t<a id=\"commitSearch\" ");
          out.write(" type=\"button\" target=\"myFrame\" class=\"btn btn-default\" style=\"float:right;margin-right:5%\" onclick=\"startSearch()\">检索维修记录</a>\r\n");
          out.write("\t\t\t");
          out.write("\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t\t<br />\r\n");
          out.write("\t\t<div class=\"searchCondition\" id=\"conditions\">\r\n");
          out.write("\t\t\t<div class=\"searchCondition-building\" id=\"buildingCondition\">\r\n");
          out.write("\t\t\t\t<select id=\"building\" class=\"form-control\" style=\"width: 30%;\">\r\n");
          out.write("\t\t\t\t\t<option value=\"0\">综合教学一号楼</option>\r\n");
          out.write("\t\t\t\t\t<option value=\"6\">综合教学二号楼</option>\r\n");
          out.write("\t\t\t\t\t<option value=\"3\">一馆</option>\r\n");
          out.write("\t\t\t\t\t<option value=\"4\">二馆</option>\r\n");
          out.write("\t\t\t\t\t<option value=\"5\">建馆</option>\r\n");
          out.write("\t\t\t\t\t<option value=\"1\">研教楼</option>\r\n");
          out.write("\t\t\t\t\t<option value=\"7\">机械馆</option>\r\n");
          out.write("\t\t\t\t\t<option value=\"8\">材料馆</option>\r\n");
          out.write("\t\t\t\t</select>\r\n");
          out.write("\t\t\t\t<!--<input type=\"text\" class=\"form-control\" id=\"personVal\" style=\"width: 30%\">-->\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t\t\r\n");
          out.write("\t\t\t<!--<div class=\"searchCondition-building\" id=\"buildingCondition\">\r\n");
          out.write("\t\t\t\t<select id=\"building\" class=\"form-control\" style=\"width: 20%; float: left\">\r\n");
          out.write("\t\t\t\t\t<option value=\"0\">一馆</option>\r\n");
          out.write("\t\t\t\t\t<option value=\"1\">综合教学一号楼</option>\r\n");
          out.write("\t\t\t\t</select>\r\n");
          out.write("\t\t\t\t<select id=\"classroom\" class=\"form-control\" style=\"width: 20%\">\r\n");
          out.write("\t\t\t\t\t<option value=\"0\">101</option>\r\n");
          out.write("\t\t\t\t\t<option value=\"1\">205</option>\r\n");
          out.write("\t\t\t\t</select>\r\n");
          out.write("\t\t\t</div>-->\r\n");
          out.write("\t\t\t\r\n");
          out.write("\t\t\t<div class=\"searchCondition-equipment\" id=\"equipmentCondition\">\r\n");
          out.write("\t\t\t\t<select id=\"deviceid\" class=\"form-control\" style=\"width: 30%\">\r\n");
          out.write("\t\t\t\t\t<option value=\"计算机\">计算机</option>\r\n");
          out.write("\t\t\t\t\t<option value=\"投影\">投影</option>\r\n");
          out.write("\t\t\t\t\t<option value=\"中央控制器\">中央控制器</option>\r\n");
          out.write("\t\t\t\t\t<option value=\"外围设备\">外围设备</option>\r\n");
          out.write("\t\t\t\t</select>\r\n");
          out.write("\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t\t\r\n");
          out.write("\t\t\t<div class=\"searchCondition-time\" id=\"timeCondition\">\r\n");
          out.write("\t\t\t\t<!-- <select id=\"time\" class=\"form-control\" style=\"width: 30%\">\r\n");
          out.write("\t\t\t\t\t<option value=\"0\">2015年9月</option>\r\n");
          out.write("\t\t\t\t\t<option value=\"1\">2015年8月</option>\r\n");
          out.write("\t\t\t\t\t<option value=\"2\">2015年7月</option>\r\n");
          out.write("\t\t\t\t\t<option value=\"3\">2015年6月</option>\r\n");
          out.write("\t\t\t\t</select> -->\r\n");
          out.write("\t\t\t\t<div class=\"form-group\" style=\"margin-bottom:-0.5%;\">\r\n");
          out.write("\t    \t\t\t<label for=\"startTime\">开始时间</label>\r\n");
          out.write("\t\t\t\t\t<input id=\"startTime\" type=\"date\" value=\"2015-09-30\"></input>\r\n");
          out.write("\t\t\t\t\t<label for=\"endTime\">结束时间</label>\r\n");
          out.write("\t\t\t\t\t<input id=\"endTime\" type=\"date\" value=\"2015-10-01\"></input>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t<!--\r\n");
          out.write("\t\t\t\t<script type=\"text/javascript\" src=\"../../js/admin/Calendar3.js\"></script>\r\n");
          out.write("\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t<td>\r\n");
          out.write("\t\t\t\t\t\t\t开始时间：\r\n");
          out.write("\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t<td>\r\n");
          out.write("\t\t\t\t\t\t\t<input type=\"text\" size=\"20\" maxlength=\"10\" id=\"startTime\" style=\"width: 15%\" \r\n");
          out.write("\t\t\t\t\t\t\t\t\tonclick=\"new Calendar().show(this);\" readonly=\"readonly\">\r\n");
          out.write("\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t<td>\r\n");
          out.write("\t\t\t\t\t\t\t结束时间：\r\n");
          out.write("\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t<td>\r\n");
          out.write("\t\t\t\t\t\t\t<input type=\"text\" size=\"20\" maxlength=\"10\" id=\"endTime\" style=\"width: 15%\" \r\n");
          out.write("\t\t\t\t\t\t\t\tonclick=\"new Calendar().show(this);\" readonly=\"readonly\">\r\n");
          out.write("\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t  -->\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t\t\r\n");
          out.write("\t\t<br />\r\n");
          out.write("\t\t<p>\r\n");
          out.write("\t\t\t <!-- <script language=\"javascript\" type=\"text/javascript\">\r\n");
          out.write("\t\t\t\t//var items=$(\":radio:checked\"); //获取选中的项 \r\n");
          out.write("\r\n");
          out.write("\t\t\t\t//alert(items.val()); //拿到选中项的值 \r\n");
          out.write("\t\t\t</script> -->\r\n");
          out.write("\t\t<p/>\r\n");
          out.write("\t\t");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t<div id=\"maintainRecords_table\">\r\n");
          out.write("\t\t\t<iframe name=\"myFrame\" frameborder=\"0\" scrolling=\"no\" style=\"width:100%;\" height=\"200px\" src=\"/jsp/admin/record_query.jsp\"></iframe>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t</div>\r\n");
          out.write("\r\n");
          out.write("\t<script language=\"javascript\" type=\"text/javascript\">\r\n");
          out.write("\t\t\r\n");
          out.write("\t</script>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t<script>\r\n");
          out.write("\t\r\n");
          out.write("\t\tfunction sc_condition(type,val)\r\n");
          out.write("\t\t{\r\n");
          out.write("\t\t\tvar href=\"");
          out.print(path);
          out.write("/admin/classroomDevice/query_action\";\r\n");
          out.write("\t\t\t\r\n");
          out.write("\t\t\thref=href+\"?Type=\"+type+\"&Value=\"+val;\r\n");
          out.write("\t\t\t//alert(href);\r\n");
          out.write("\t\t\tdocument.getElementById(\"commitSearch\").href=href;\r\n");
          out.write("\t\t\t/* alert(type + \":\" +val); */\r\n");
          out.write("\t\t}\r\n");
          out.write("\t\tfunction sc_building() {\r\n");
          out.write("\t\t\t\r\n");
          out.write("\t\t\tvar optionval = $(\"#building option:selected\").val();\r\n");
          out.write("\t\t\tsc_condition('1',optionval);\r\n");
          out.write("\t\t}\r\n");
          out.write("\t\t\r\n");
          out.write("\t\t\r\n");
          out.write("\t\tfunction sc_device() {\r\n");
          out.write("\t\t\tvar optionval = $(\"#deviceid option:selected\").val();\r\n");
          out.write("\t\t\tsc_condition('2',optionval);\r\n");
          out.write("\t\t}\r\n");
          out.write("\t\t\r\n");
          out.write("\t\tfunction sc_time() {\r\n");
          out.write("\t\t\t/* var optionval = $(\"#time option:selected\").val() */\r\n");
          out.write("\t\t\tvar str = $(\"#startTime\").val();\r\n");
          out.write("\t\t\tvar end = $(\"#endTime\").val();\r\n");
          out.write("\t\t\toptionval = str +\":\"+ end;\r\n");
          out.write("\t\t\tsc_condition('3',optionval);\r\n");
          out.write("\t\t}\r\n");
          out.write("\t\t\r\n");
          out.write("\t\tfunction startSearch() {\r\n");
          out.write("\t\t\tvar items=$(\":radio:checked\"); //获取选中的项;\r\n");
          out.write("\t\t\tswitch (parseInt(items.val())) {\r\n");
          out.write("\t\t\t\tcase 0:\r\n");
          out.write("\t\t\t\t\tsc_building();\r\n");
          out.write("\t\t\t\t\tbreak;\r\n");
          out.write("\t\t\t\tcase 2:\r\n");
          out.write("\t\t\t\t\tsc_device();\r\n");
          out.write("\t\t\t\t\tbreak;\r\n");
          out.write("\t\t\t\tcase 3:\r\n");
          out.write("\t\t\t\t\tsc_time();\r\n");
          out.write("\t\t\t\t\tbreak;\r\n");
          out.write("\t\t\t\tdefault:\r\n");
          out.write("\t\t\t\t\talert(\"ERROR:Wrong val.\");\r\n");
          out.write("\t\t\t\t\treturn false;\r\n");
          out.write("\t\t\t} \r\n");
          out.write("\t\t\treturn true;\r\n");
          out.write("\t\t}\r\n");
          out.write("\t\r\n");
          out.write("\t\tfunction showdiv(objId) {\r\n");
          out.write("\t\t\t$('#buildingCondition').hide();\r\n");
          out.write("\t\t\t$('#equipmentCondition').hide();\r\n");
          out.write("\t\t\t$('#timeCondition').hide();\r\n");
          out.write("\t\t\t$(objId).show();\r\n");
          out.write("\t\t\treturn true;\r\n");
          out.write("\t\t}\r\n");
          out.write("\t\tfunction hidediv(objId) {\r\n");
          out.write("\t\t\tdocument.getElementById(objId).style.display = \"none\";\r\n");
          out.write("\t\t}\r\n");
          out.write("\t\t$(window).load(function() {\r\n");
          out.write("\t\t\t$('#buildingCondition').show();\r\n");
          out.write("\t\t\t//$('#buildingCondition').hide();\r\n");
          out.write("\t\t\t$('#equipmentCondition').hide();\r\n");
          out.write("\t\t\t$('#timeCondition').hide();\r\n");
          out.write("\t\t});\r\n");
          out.write("\r\n");
          out.write("\t\tfunction ClassroomSearchCallback(data) {\r\n");
          out.write("\t\t\tif (data.status == \"0\") {\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t$(\"#classroom_search_table\").html(data.classroominfo.html);\r\n");
          out.write("\t\t\t\tanimatedShow(\"查询成功\");\r\n");
          out.write("\t\t\t} else if (data.status == \"1\") {\r\n");
          out.write("\t\t\t\tanimatedShow(\"查询关键字为空\");\r\n");
          out.write("\t\t\t} else {\r\n");
          out.write("\t\t\t\talert(\"error with status\" + data.status);\r\n");
          out.write("\t\t\t}\r\n");
          out.write("\t\t\t//$(\"#add_new_courseplan\").attr(\"disabled\",false);\r\n");
          out.write("\r\n");
          out.write("\t\t\t//     \talert($(document).find(\"#added_user_tr\").html());\r\n");
          out.write("\t\t\t//     \talert(data.added_user_html);\r\n");
          out.write("\t\t\t//     \talert(data.username);\r\n");
          out.write("\t\t}\r\n");
          out.write("\t</script>\r\n");
          int evalDoAfterBody = _jspx_th_layout_005foverride_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_layout_005foverride_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_layout_005foverride_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname.reuse(_jspx_th_layout_005foverride_005f0);
        return;
      }
      _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname.reuse(_jspx_th_layout_005foverride_005f0);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005foverride_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005foverride_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("    \t\r\n");
      out.write("    \t");
      if (_jspx_meth_layout_005fblock_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        <meta charset=\"utf-8\"/>\r\n");
      out.write("        <meta name=\"renderer\" content=\"webkit\"/>\r\n");
      out.write("        <title>多媒体管理系统</title>\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("        <meta name=\"keywords\" content=\"\" />\r\n");
      out.write("        <meta name=\"author\" content=\"\" />\r\n");
      out.write("\t\t<script type='text/javascript' src=\"/js/base/myutil.js\"></script>\r\n");
      out.write("        <link href=\"/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t\t<link href=\"/bootstrap/css/bootstrap-theme.min.css\" rel=\"stylesheet\" />\t\t\r\n");
      out.write("\t\t<link href=\"/datepicker/css/bootstrap-datetimepicker.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("        <script type='text/javascript' src=\"/js/base/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("        <script type='text/javascript' src=\"/datepicker/js/bootstrap-datetimepicker.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/datepicker/js/bootstrap-datetimepicker.zh-CN.js\" charset=\"UTF-8\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"/css/base/table.css\" >\t\t\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"/css/base/base.css\"/> \r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"/css/admin/classroom_manage.css\"/>\r\n");
      out.write("\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"/css/base/websocket.css\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      if (_jspx_meth_layout_005fblock_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </head>   \r\n");
      out.write("\r\n");
      out.write("    <body >\r\n");
      out.write("\t\t<div id=\"basecontent\">\t\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_layout_005fblock_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    \t</div>\r\n");
      out.write("\t\t<footer class=\"container\" style=\"text-align:center\">\r\n");
      out.write("\t\t  <p>Copyright © 1986 - 2016 All rights reserved | <a href=\"http://chuangxin.dlut.edu.cn\">大连理工大学创新实验学院版权所有</a> | GPLv3 <a href=\"http://gplv3.fsf.org/\">Terms</a></p>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("        <script type='text/javascript' src=\"/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!--TinyMCE Editor-->\r\n");
      out.write("\t\t<script type='text/javascript' src=\"/js/base/tiny_mce.js\"></script>\r\n");
      out.write("\t\t<!-- JQuery Masonry-->\r\n");
      out.write("\t\t<script type='text/javascript' src=\"/js/base/jquery.masonry.min.js\"></script>\r\n");
      out.write("\t\t<script type='text/javascript' src=\"/js/base/base.js\"></script>\t\t       \r\n");
      out.write("        <!-- 百度推广JS -->\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("            var _bdhmProtocol = ((\"https:\" == document.location.protocol) ? \" https://\" : \" http://\");\r\n");
      out.write("        </script>\r\n");
      out.write("         <!-- 百度推广JS END -->\r\n");
      out.write("        </body>\r\n");
      out.write("    </html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \t");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005foverride_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:override
    tags.OverrideTag _jspx_th_layout_005foverride_005f1 = (tags.OverrideTag) _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname.get(tags.OverrideTag.class);
    _jspx_th_layout_005foverride_005f1.setPageContext(_jspx_page_context);
    _jspx_th_layout_005foverride_005f1.setParent(null);
    // /jsp/admin/base.jsp(5,0) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_layout_005foverride_005f1.setName("menu_list");
    int _jspx_eval_layout_005foverride_005f1 = _jspx_th_layout_005foverride_005f1.doStartTag();
    if (_jspx_eval_layout_005foverride_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_layout_005foverride_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_layout_005foverride_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_layout_005foverride_005f1.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("\r\n");
        out.write("\t<div class=\"menu-list\">\r\n");
        out.write("\t    <a href=\"/admin/classroom/\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-blackboard\">&nbsp;教室管理</span></a>\r\n");
        out.write("\t    <a href=\"/admin/repertory\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-th-large\">&nbsp;设备管理</span></a>\r\n");
        out.write("\t    <a href=\"/admin/classroomDevice/maintainRecords\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-th\">&nbsp;维修记录管理</span></a>\r\n");
        out.write("\t    <a href=\"/admin/student_manage/\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-list-alt\">&nbsp;在职学生管理</span></a>\r\n");
        out.write("\t    <a href=\"/admin/user_request/\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-list-alt\">&nbsp;用户注册请求</span></a>\r\n");
        out.write("\t    \r\n");
        out.write("\t    <a href=\"/admin/usefdsaf\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-list-alt\">&nbsp;账号生成</span></a>\r\n");
        out.write("\r\n");
        out.write("<!-- \t    <a href=\"/admin/wer\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-list-alt\">&nbsp;主页修改</span></a> -->\r\n");
        out.write("<!-- \t    <a href=\"/admin/notice\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-list-alt\">&nbsp;公告管理</span></a> -->\r\n");
        out.write("\r\n");
        out.write("\t    <a href=\"/admin/HomepageModify/\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-list-alt\">&nbsp;主页修改</span></a>\r\n");
        out.write("\t    <a href=\"/admin/adf\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-list-alt\">&nbsp;日志管理</span></a>\r\n");
        out.write("\t    <a href=\"/admin/asdf\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-list-alt\">&nbsp;远程控制</span></a>\r\n");
        out.write("\t    <a href=\"/admin/modifypassword\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-lock\">&nbsp;修改密码</span></a>\r\n");
        out.write("\t    <a href=\"/admin/user_information\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-list-alt\">&nbsp;个人信息</span></a>\r\n");
        out.write("\t    <a href=\"/logout\" class=\"menu-button-middle\"><span class=\"glyphicon glyphicon-list-alt\">&nbsp;安全退出</span></a>\r\n");
        out.write("\t    <div class=\"menu-blank\"></div>\r\n");
        out.write("\t</div>\r\n");
        out.write("\t\r\n");
        out.write("\t \r\n");
        out.write(" ");
        int evalDoAfterBody = _jspx_th_layout_005foverride_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_layout_005foverride_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_layout_005foverride_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname.reuse(_jspx_th_layout_005foverride_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname.reuse(_jspx_th_layout_005foverride_005f1);
    return false;
  }

  private boolean _jspx_meth_layout_005foverride_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:override
    tags.OverrideTag _jspx_th_layout_005foverride_005f2 = (tags.OverrideTag) _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname.get(tags.OverrideTag.class);
    _jspx_th_layout_005foverride_005f2.setPageContext(_jspx_page_context);
    _jspx_th_layout_005foverride_005f2.setParent(null);
    // /jsp/base/user_base.jsp(3,0) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_layout_005foverride_005f2.setName("base_content");
    int _jspx_eval_layout_005foverride_005f2 = _jspx_th_layout_005foverride_005f2.doStartTag();
    if (_jspx_eval_layout_005foverride_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_layout_005foverride_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_layout_005foverride_005f2.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_layout_005foverride_005f2.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("\t\r\n");
        out.write("<a href=\"/\">\r\n");
        out.write("    <div id=\"headerpic\" >\r\n");
        out.write("        <ul class=\"nav navbar-right\">\r\n");
        out.write("            <li id=\"welcome_word\">\r\n");
        out.write("            \t欢迎您: <span id=\"login_user_name\">");
        if (_jspx_meth_s_005fproperty_005f0(_jspx_th_layout_005foverride_005f2, _jspx_page_context))
          return true;
        out.write("</span>\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("<!--             \t<p></p> -->\r\n");
        out.write("            \t\r\n");
        out.write("            \t");
        if (_jspx_meth_s_005fif_005f0(_jspx_th_layout_005foverride_005f2, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("            \t");
        if (_jspx_meth_s_005felse_005f0(_jspx_th_layout_005foverride_005f2, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("            \t\r\n");
        out.write("            \t\r\n");
        out.write("            </li>\r\n");
        out.write("        </ul>\r\n");
        out.write("    </div>\r\n");
        out.write("</a>\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("<div class=\"container-fluid main-container\">\r\n");
        out.write("    <div class=\"row col-lg-12\">\r\n");
        out.write("        <div class=\"col-lg-3 \">\t                    \r\n");
        out.write("            ");
        if (_jspx_meth_layout_005fblock_005f0(_jspx_th_layout_005foverride_005f2, _jspx_page_context))
          return true;
        out.write("\t\r\n");
        out.write("        </div>\r\n");
        out.write("        <div class=\"col-lg-9\">\r\n");
        out.write("        \t<div class=\"main-content\">\r\n");
        out.write("            \t");
        if (_jspx_meth_layout_005fblock_005f1(_jspx_th_layout_005foverride_005f2, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("         </div>\r\n");
        out.write("        </div>\r\n");
        out.write("    </div>\r\n");
        out.write("</div>\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("<!-- \r\n");
        out.write("<div id=\"envelope\"></div>\r\n");
        out.write("<div id=\"message-list-box\" class=\"hide\">\r\n");
        out.write("\t<div class=\"message-list-top\">\r\n");
        out.write("\t\t<span class=\"title\">消息</span>\r\n");
        out.write("\t\t<span class=\"glyphicon glyphicon-remove closed\"></span>\r\n");
        out.write("\t\t<span class=\"glyphicon glyphicon-user users\"></span>\r\n");
        out.write("\t</div>\r\n");
        out.write("\t<div class=\"message-list\"></div>\r\n");
        out.write("\t<div class=\"message-list-bottom\" id=\"write-message\">\r\n");
        out.write("\t\t<span>发信息</span>\r\n");
        out.write("\t</div>\r\n");
        out.write("</div>\r\n");
        out.write("\r\n");
        out.write("<div id=\"message-contacts-box\" class=\"hide\">\r\n");
        out.write("\t<div class=\"message-contacts-top\">\r\n");
        out.write("\t\t<span class=\"title\">联系人</span>\r\n");
        out.write("\t\t<span class=\"glyphicon glyphicon-remove closed\"></span>\r\n");
        out.write("\t</div>\r\n");
        out.write("\t<div class=\"message-contacts\">\r\n");
        out.write("    \t<h4>\r\n");
        out.write("        \t<a class=\"contacts-expand collapsed\" data-toggle=\"collapse\" href=\"#admin-contacts\" aria-expanded=\"false\" aria-controls=\"admin-contacts\">\r\n");
        out.write("          \t\t<span class=\"glyphicon glyphicon-plus\"></span>  管理员\r\n");
        out.write("        \t</a>\r\n");
        out.write("      \t</h4>\r\n");
        out.write("    \t<div id=\"admin-contacts\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingOne\">\r\n");
        out.write("      \t\t<ul class=\"contacts-list-group list-group\"></ul>\r\n");
        out.write("    \t</div>\r\n");
        out.write("\t    <h4>\r\n");
        out.write("\t        <a class=\"contacts-expand collapsed\" data-toggle=\"collapse\" href=\"#teacher-contacts\" aria-expanded=\"false\" aria-controls=\"teacher-contacts\">\r\n");
        out.write("\t          \t<span class=\"glyphicon glyphicon-plus\"></span>  教师\r\n");
        out.write("\t        </a>\r\n");
        out.write("\t    </h4>\r\n");
        out.write("\t    <div id=\"teacher-contacts\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingTwo\">\r\n");
        out.write("\t      \t<ul class=\"contacts-list-group list-group\"></ul>\r\n");
        out.write("\t    </div>\r\n");
        out.write("\t    <h4>\r\n");
        out.write("\t        <a class=\"contacts-expand collapsed\" data-toggle=\"collapse\" href=\"#student-contacts\" aria-expanded=\"false\" aria-controls=\"student-contacts\">\r\n");
        out.write("\t          \t<span class=\"glyphicon glyphicon-plus\"></span>  学生\r\n");
        out.write("\t        </a>\r\n");
        out.write("\t    </h4>\r\n");
        out.write("\t    <div id=\"student-contacts\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingTwo\">\r\n");
        out.write("\t      \t<ul class=\"contacts-list-group list-group\"></ul>\r\n");
        out.write("\t    </div>\r\n");
        out.write("\t</div>\r\n");
        out.write("</div>\r\n");
        out.write("\r\n");
        out.write("<div id=\"message-content-box\" class=\"hide\" from=");
        if (_jspx_meth_s_005fproperty_005f1(_jspx_th_layout_005foverride_005f2, _jspx_page_context))
          return true;
        out.write(">\r\n");
        out.write("\t<div class=\"message-content-top\">\r\n");
        out.write("\t\t<span class=\"title\">某某某</span>\r\n");
        out.write("\t\t<span class=\"glyphicon glyphicon-remove closed\"></span>\r\n");
        out.write("\t\t<span class=\"glyphicon glyphicon-user users\"></span>\r\n");
        out.write("\t\t<span class=\"glyphicon glyphicon-menu-left back\"></span>\r\n");
        out.write("\t</div>\r\n");
        out.write("\t<div class=\"message-content\"></div>\r\n");
        out.write("\t<div class=\"message-tool\"></div>\r\n");
        out.write("\t<div class=\"message-writeboard\">\r\n");
        out.write("\t\t<textarea class=\"form-control\" rows=\"4\"></textarea>\r\n");
        out.write("\t\t<div class=\"send-bottom\">\r\n");
        out.write("\t\t\t<button type=\"button\" class=\"btn btn-sm\" onclick=\"sendMessage()\">发送</button>\r\n");
        out.write("\t\t</div>\r\n");
        out.write("\t</div>\r\n");
        out.write("</div>\r\n");
        out.write("\r\n");
        out.write("<script type=\"text/javascript\" src=\"/js/base/websocket.js\"></script>\r\n");
        out.write(" -->\r\n");
        out.write("        \r\n");
        out.write(" ");
        if (_jspx_meth_layout_005fblock_005f2(_jspx_th_layout_005foverride_005f2, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\r\n");
        out.write("\r\n");
        out.write("\t\r\n");
        out.write("\t\r\n");
        int evalDoAfterBody = _jspx_th_layout_005foverride_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_layout_005foverride_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_layout_005foverride_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname.reuse(_jspx_th_layout_005foverride_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname.reuse(_jspx_th_layout_005foverride_005f2);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_layout_005foverride_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f0 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_layout_005foverride_005f2);
    // /jsp/base/user_base.jsp(9,45) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f0.setValue("#session.username");
    int _jspx_eval_s_005fproperty_005f0 = _jspx_th_s_005fproperty_005f0.doStartTag();
    if (_jspx_th_s_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_layout_005foverride_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:if
    org.apache.struts2.views.jsp.IfTag _jspx_th_s_005fif_005f0 = (org.apache.struts2.views.jsp.IfTag) _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.get(org.apache.struts2.views.jsp.IfTag.class);
    _jspx_th_s_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_layout_005foverride_005f2);
    // /jsp/base/user_base.jsp(14,13) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fif_005f0.setTest("#session.role.equals(@util.Const@AdminRole)");
    int _jspx_eval_s_005fif_005f0 = _jspx_th_s_005fif_005f0.doStartTag();
    if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fif_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fif_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("            \t\t(您是管理员)\r\n");
        out.write("            \t");
        int evalDoAfterBody = _jspx_th_s_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005felse_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_layout_005foverride_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:else
    org.apache.struts2.views.jsp.ElseTag _jspx_th_s_005felse_005f0 = (org.apache.struts2.views.jsp.ElseTag) _005fjspx_005ftagPool_005fs_005felse.get(org.apache.struts2.views.jsp.ElseTag.class);
    _jspx_th_s_005felse_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005felse_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_layout_005foverride_005f2);
    int _jspx_eval_s_005felse_005f0 = _jspx_th_s_005felse_005f0.doStartTag();
    if (_jspx_eval_s_005felse_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005felse_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005felse_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005felse_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("            \t\t(您是在职学生)\r\n");
        out.write("            \t");
        int evalDoAfterBody = _jspx_th_s_005felse_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005felse_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005felse_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005felse.reuse(_jspx_th_s_005felse_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005felse.reuse(_jspx_th_s_005felse_005f0);
    return false;
  }

  private boolean _jspx_meth_layout_005fblock_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_layout_005foverride_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:block
    tags.BlockTag _jspx_th_layout_005fblock_005f0 = (tags.BlockTag) _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.get(tags.BlockTag.class);
    _jspx_th_layout_005fblock_005f0.setPageContext(_jspx_page_context);
    _jspx_th_layout_005fblock_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_layout_005foverride_005f2);
    // /jsp/base/user_base.jsp(33,12) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_layout_005fblock_005f0.setName("menu_list");
    int _jspx_eval_layout_005fblock_005f0 = _jspx_th_layout_005fblock_005f0.doStartTag();
    if (_jspx_eval_layout_005fblock_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("            ");
        int evalDoAfterBody = _jspx_th_layout_005fblock_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_layout_005fblock_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f0);
    return false;
  }

  private boolean _jspx_meth_layout_005fblock_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_layout_005foverride_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:block
    tags.BlockTag _jspx_th_layout_005fblock_005f1 = (tags.BlockTag) _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.get(tags.BlockTag.class);
    _jspx_th_layout_005fblock_005f1.setPageContext(_jspx_page_context);
    _jspx_th_layout_005fblock_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_layout_005foverride_005f2);
    // /jsp/base/user_base.jsp(38,13) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_layout_005fblock_005f1.setName("main_content");
    int _jspx_eval_layout_005fblock_005f1 = _jspx_th_layout_005fblock_005f1.doStartTag();
    if (_jspx_eval_layout_005fblock_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("            \t");
        int evalDoAfterBody = _jspx_th_layout_005fblock_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_layout_005fblock_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f1);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_layout_005foverride_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f1 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_layout_005foverride_005f2);
    // /jsp/base/user_base.jsp(93,48) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f1.setValue("#session.user_id");
    int _jspx_eval_s_005fproperty_005f1 = _jspx_th_s_005fproperty_005f1.doStartTag();
    if (_jspx_th_s_005fproperty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f1);
    return false;
  }

  private boolean _jspx_meth_layout_005fblock_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_layout_005foverride_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:block
    tags.BlockTag _jspx_th_layout_005fblock_005f2 = (tags.BlockTag) _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.get(tags.BlockTag.class);
    _jspx_th_layout_005fblock_005f2.setPageContext(_jspx_page_context);
    _jspx_th_layout_005fblock_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_layout_005foverride_005f2);
    // /jsp/base/user_base.jsp(113,1) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_layout_005fblock_005f2.setName("nav_content");
    int _jspx_eval_layout_005fblock_005f2 = _jspx_th_layout_005fblock_005f2.doStartTag();
    if (_jspx_eval_layout_005fblock_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write(" \r\n");
        out.write(" ");
        int evalDoAfterBody = _jspx_th_layout_005fblock_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_layout_005fblock_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f2);
    return false;
  }

  private boolean _jspx_meth_layout_005fblock_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:block
    tags.BlockTag _jspx_th_layout_005fblock_005f3 = (tags.BlockTag) _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.get(tags.BlockTag.class);
    _jspx_th_layout_005fblock_005f3.setPageContext(_jspx_page_context);
    _jspx_th_layout_005fblock_005f3.setParent(null);
    // /jsp/base/base.jsp(12,5) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_layout_005fblock_005f3.setName("head_begin");
    int _jspx_eval_layout_005fblock_005f3 = _jspx_th_layout_005fblock_005f3.doStartTag();
    if (_jspx_eval_layout_005fblock_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("    \t");
        int evalDoAfterBody = _jspx_th_layout_005fblock_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_layout_005fblock_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f3);
    return false;
  }

  private boolean _jspx_meth_layout_005fblock_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:block
    tags.BlockTag _jspx_th_layout_005fblock_005f4 = (tags.BlockTag) _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.get(tags.BlockTag.class);
    _jspx_th_layout_005fblock_005f4.setPageContext(_jspx_page_context);
    _jspx_th_layout_005fblock_005f4.setParent(null);
    // /jsp/base/base.jsp(38,2) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_layout_005fblock_005f4.setName("head_end");
    int _jspx_eval_layout_005fblock_005f4 = _jspx_th_layout_005fblock_005f4.doStartTag();
    if (_jspx_eval_layout_005fblock_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\r\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_layout_005fblock_005f4.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_layout_005fblock_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f4);
    return false;
  }

  private boolean _jspx_meth_layout_005fblock_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:block
    tags.BlockTag _jspx_th_layout_005fblock_005f5 = (tags.BlockTag) _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.get(tags.BlockTag.class);
    _jspx_th_layout_005fblock_005f5.setPageContext(_jspx_page_context);
    _jspx_th_layout_005fblock_005f5.setParent(null);
    // /jsp/base/base.jsp(45,3) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_layout_005fblock_005f5.setName("base_content");
    int _jspx_eval_layout_005fblock_005f5 = _jspx_th_layout_005fblock_005f5.doStartTag();
    if (_jspx_eval_layout_005fblock_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_layout_005fblock_005f5.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_layout_005fblock_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f5);
    return false;
  }
}
