/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2015-10-10 06:52:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.homepage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_005fregister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/jsp_layout.tld", Long.valueOf(1443426900023L));
    _jspx_dependants.put("/jsp/homepage/new_home_base.jsp", Long.valueOf(1443432156532L));
    _jspx_dependants.put("jar:file:/D:/MyCodes/Java/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DuoMeiTi/WEB-INF/lib/struts2-core-2.3.24.jar!/META-INF/struts-tags.tld", Long.valueOf(1430627084000L));
    _jspx_dependants.put("/jsp/base/taglib.jsp", Long.valueOf(1443426900665L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.3.24.jar", Long.valueOf(1443426900605L));
    _jspx_dependants.put("/WEB-INF/pagetag.tld", Long.valueOf(1443426900613L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fselect_0026_005fstyle_005fname_005flist_005fid_005fclass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fdebug_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fselect_0026_005fstyle_005fname_005flist_005fid_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fdebug_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname.release();
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fselect_0026_005fstyle_005fname_005flist_005fid_005fclass_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fdebug_005fnobody.release();
    _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005foverride_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("    <meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("    <title>多媒体管理系统</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    \r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    \r\n");
      out.write("    <meta name=\"keywords\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("    <!-- CSS Config. -->\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write(" <!-- Le styles -->\r\n");
      out.write(" \r\n");
      out.write("         <link href=\"/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t\t<link href=\"/bootstrap/css/bootstrap-theme.min.css\" rel=\"stylesheet\" />\t\t\r\n");
      out.write("\t\t<link href=\"/datepicker/css/bootstrap-datetimepicker.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("        <script type='text/javascript' src=\"/js/base/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("        <script type='text/javascript' src=\"/datepicker/js/bootstrap-datetimepicker.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/datepicker/js/bootstrap-datetimepicker.zh-CN.js\" charset=\"UTF-8\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"/new_homepage/style/common/base.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"/new_homepage/style/common/content.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"/new_homepage/style/home/content.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">object,embed{                -webkit-animation-duration:.001s;-webkit-animation-name:playerInserted;                -ms-animation-duration:.001s;-ms-animation-name:playerInserted;                -o-animation-duration:.001s;-o-animation-name:playerInserted;                animation-duration:.001s;animation-name:playerInserted;}                @-webkit-keyframes playerInserted{from{opacity:0.99;}to{opacity:1;}}                @-ms-keyframes playerInserted{from{opacity:0.99;}to{opacity:1;}}                @-o-keyframes playerInserted{from{opacity:0.99;}to{opacity:1;}}                @keyframes playerInserted{from{opacity:0.99;}to{opacity:1;}}</style></head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <a href=\"/\">\r\n");
      out.write("  \t<div id=\"headerpic\" style=\"height:80px;\">\r\n");
      out.write("\t</div>\r\n");
      out.write("  </a>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"container\" id=\"nav-container\">\r\n");
      out.write("\r\n");
      out.write("\t       \r\n");
      out.write("\t       \r\n");
      out.write("       <!--head content-->\r\n");
      out.write("       <div class=\"masthead\">\r\n");
      out.write("\t         <!--Head title-->\r\n");
      out.write("<!-- \t         <a href=\"/\"><h1 class=\"muted head-title\">大连理工大学基本科研业务费管理平台</h1></a> -->\r\n");
      out.write("<!-- \t         <p class=\"head-title-low\">Dalian University of Technology Fundamental Research Fund Management Platform</p> -->\r\n");
      out.write("<!-- \t         <hr class=\"head-hr\"> -->\r\n");
      out.write("\t\t\t        \r\n");
      out.write("\t\t\t   <div class=\"container\">\r\n");
      out.write("\t\t\t     <nav class=\"navbar navbar-default\" role=\"navigation\">\r\n");
      out.write("\t\t\t       <div class=\"collapse navbar-collapse\">\r\n");
      out.write("\t\t\t         <ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t           <li class=\"\"><a href=\"/\">首页</a></li>\r\n");
      out.write("\t\t\t           <li class=\"\"><a href=\"/ClassroomFile\">教室信息</a></li>\r\n");
      out.write("\t\t\t           <li class=\"\"><a href=\"\">通讯录</a></li>\r\n");
      out.write("\t\t\t           <li class=\"\"><a href=\"\">常见问题</a></li>\r\n");
      out.write("\t\t\t           \r\n");
      out.write("\t\t\t           <li class=\"\"><a href=\"/login\">登录</a></li>\r\n");
      out.write("\t\t\t           <li class=\"dropdown\">\r\n");
      out.write("\t\t\t             <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">注册\r\n");
      out.write("\t\t\t               <b class=\"caret\"></b>\r\n");
      out.write("\t\t\t             </a>\r\n");
      out.write("\t\t\t             <ul class=\"dropdown-menu home_menu\" role=\"menu\">\r\n");
      out.write("\t\t\t               <li><a href=\"/admin_register\">系统管理员</a></li>\r\n");
      out.write("\t\t\t               <li><a href=\"/student_register\">在职学生</a></li>\r\n");
      out.write("\t\t\t               <li><a href=\"/accounts/expertlogin\">授课教师</a></li>\t\t\t               \r\n");
      out.write("\t\t\t             </ul>\r\n");
      out.write("\t\t\t           </li>\r\n");
      out.write("\t\t\t           \r\n");
      out.write("\t\t\t           \r\n");
      out.write("\t\t\t         </ul>\r\n");
      out.write("\t\t\t       </div>\r\n");
      out.write("\t\t\t     </nav>\r\n");
      out.write("\t\t\t   </div><!--end navbar-->\r\n");
      out.write("   \r\n");
      out.write("       </div><!--end mashhead-->\r\n");
      out.write("    </div><!--end whole container-->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   <!--different page content-->\r\n");
      out.write("   \r\n");
      out.write("<!-- <div class=\"homepage-picture\"> -->\r\n");
      out.write("<!--   <div id=\"myCarousel\" class=\"carousel slide\" style=\"width:100%; height:300px\"> -->\r\n");
      out.write("<!--   <div class=\"carousel-inner\" style=\"height:100%\"> -->\r\n");
      out.write("    \r\n");
      out.write("<!--       <div class=\"item  active \"> -->\r\n");
      out.write("<!--         <img src=\"/new_homepage/homepage_pic/2.jpg\" alt=\"\"> -->\r\n");
      out.write("<!--         <div class=\"carousel-caption\"> -->\r\n");
      out.write("<!--         </div> -->\r\n");
      out.write("<!--       </div> -->\r\n");
      out.write("    \r\n");
      out.write("<!--   </div> -->\r\n");
      out.write("<!--   <div class=\"left my-carousel-control\"> -->\r\n");
      out.write("<!--     <a class=\"\" href=\"/#myCarousel\" data-slide=\"prev\">‹</a> -->\r\n");
      out.write("<!--   </div> -->\r\n");
      out.write("<!--   <div class=\"right my-carousel-control\"> -->\r\n");
      out.write("<!--     <a class=\"\" href=\"/#myCarousel\" data-slide=\"next\">›</a> -->\r\n");
      out.write("<!--   </div> -->\r\n");
      out.write("<!-- </div> -->\r\n");
      out.write("<!-- <!-- /.carousel --> -->\r\n");
      out.write("\r\n");
      out.write("<!-- </div> -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"container home-content-container\">\r\n");
      out.write("     \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_layout_005fblock_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!--check the browser type-->\r\n");
      out.write("\t\t\t\t<div style=\"width:45%;background-color:#f2dede;border-color: #d6e9c6;\" id=\"myModal\" class=\"modal hide fade\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t\t\t\t  <div style=\"border: 1px solid #fc6;text-align:center;\">\r\n");
      out.write("\t\t\t\t\t\t    <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">×</button>\r\n");
      out.write("\t\t\t\t\t\t    <h3>欢迎您使用创新创业管理平台</h3>\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t  <div>\r\n");
      out.write("\t\t\t\t\t\t    <div style=\"font-size:20px;padding:20px;margin-bottom:0px;\">\r\n");
      out.write("\t\t\t\t\t\t      <p class=\"text-info\">为了达到最佳浏览效果，我们推荐您使用以下浏览器</p>\r\n");
      out.write("\t\t\t\t\t\t      <p style=\"font-size:14px;color:#3a87ad\">请您<strong>点击</strong>相应的浏览器图标跳转到下载页面进行下载\r\n");
      out.write("\t\t\t\t\t\t    </p></div>\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t  <hr style=\"border-bottom: 1px solid #FFFF99;margin:0px;\">\r\n");
      out.write("\t\t\t\t\t\t  <div style=\"font-size:20px;padding:20px;margin:10px;\">\r\n");
      out.write("\t\t\t\t\t\t    <form class=\"bs-docs-example\">\r\n");
      out.write("\t\t\t\t\t\t      <center>\r\n");
      out.write("\t\t\t\t\t\t        <a href=\"http://chrome.360.cn/\" style=\"margin-right:15px;\">\r\n");
      out.write("\t\t\t\t\t\t            <img border=\"0\" style=\"width:70px;height:70px;\" src=\"/new_homepage/images/360.jpg\" title=\"360极速浏览器(下载快速)\"> \r\n");
      out.write("\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        <a href=\"http://www.google.cn/intl/zh-CN/chrome/browser/\" style=\"margin-right:15px;\">\r\n");
      out.write("\t\t\t\t\t\t          <img border=\"0\" style=\"width:70px;height:70px;\" src=\"/new_homepage/images/chrome.png\" title=\"谷歌浏览器(使用最广)\">\r\n");
      out.write("\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        <a href=\"http://www.maxthon.cn/\" style=\"margin-right:15px;\">\r\n");
      out.write("\t\t\t\t\t\t          <img border=\"0\" style=\"width:70px;height:70px;\" src=\"/new_homepage/images/maxthon-logo.png\" title=\"傲游浏览器\"> \r\n");
      out.write("\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        <a href=\"http://firefox.com.cn/download/\" style=\"margin-right:15px;\">\r\n");
      out.write("\t\t\t\t\t\t          <img border=\"0\" style=\"width:70px;height:70px;\" src=\"/new_homepage/images/browser-icon-firefox.png\" title=\"火狐浏览器\"> \r\n");
      out.write("\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        <a href=\"http://www.opera.com/zh-cn/computer/windows\" style=\"margin-right:15px;\">\r\n");
      out.write("\t\t\t\t\t\t          <img border=\"0\" style=\"width:70px;height:70px;\" src=\"/new_homepage/images/Opera.png\" title=\"Opera浏览器\"> \r\n");
      out.write("\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t        <a href=\"http://ie.sogou.com/\" style=\"margin-right:15px;\">\r\n");
      out.write("\t\t\t\t\t\t          <img border=\"0\" style=\"width:70px;height:70px;\" src=\"/new_homepage/images/sogou.jpg\" title=\"搜狗浏览器\"> \r\n");
      out.write("\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t      </center>\r\n");
      out.write("\t\t\t\t\t\t    </form>\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t  <hr style=\"border-top: 1px solid #FFFF99;margin:0px;\">\r\n");
      out.write("\t\t\t\t\t\t  <div style=\"font-size:20px;padding:20px;margin-bottom:0px;\">\r\n");
      out.write("\t\t\t\t\t\t    <p style=\"font-size:18px;\" class=\"text-success\">如果您选择使用<strong>360极速浏览器</strong>或是<strong>搜狗浏览器</strong>，我们建议您将浏览器设置为<strong>极速模式</strong>。</p>\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" src=\"/new_homepage/js/home/checkbrowser.js\"></script>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write(" <div id=\"footer-links\">\r\n");
      out.write("     <!--useful links-->\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<p class=\"item-title-white\">友情链接</p>\r\n");
      out.write("\t\t<hr class=\"head-hr\">\r\n");
      out.write("\t\t<div class=\"row-fluid\" id=\"home-linker\">\r\n");
      out.write("\t\t  <div class=\"col-lg-3\">\r\n");
      out.write("\t\t    <a href=\"http://www.dlut.edu.cn/\">大连理工大学</a>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- FOOTER -->\r\n");
      out.write("<footer class=\"container\">\r\n");
      out.write("  <p>Copyright © 1986 - 2016 All rights reserved | | GPLv3 <a href=\"http://gplv3.fsf.org/\">Terms</a></p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<!--End FOOTER-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("<!-- Le javascript\r\n");
      out.write("================================================== -->\r\n");
      out.write("<!-- Placed at the end of the document so the pages load faster -->\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"/new_homepage/bootstrap/assets/js/bootstrap.min.js\"></script> -->\r\n");
      out.write("<script type='text/javascript' src=\"/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--TinyMCE Editor-->\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"/new_homepage/tiny_mce/tiny_mce.js\"></script> -->\r\n");
      out.write("<script type='text/javascript' src=\"/js/base/tiny_mce.js\"></script>\r\n");
      out.write("<!-- JQuery Masonry-->\r\n");
      out.write("<script type='text/javascript' src=\"/js/base/jquery.masonry.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- JQuery Masonry-->\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"/new_homepage/masonry/jquery.masonry.min.js\"></script> -->\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<script type=\"text/javascript\" src=\"/new_homepage/js/features.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- 百度推广JS -->\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("  var _bdhmProtocol = ((\"https:\" == document.location.protocol) ? \" https://\" : \" http://\");\r\n");
      out.write("document.write(unescape(\"%3Cscript src='\" + _bdhmProtocol + \"hm.baidu.com/h.js%3F467a2b45543928de4d32a9f7c3bfc175' type='text/javascript'%3E%3C/script%3E\"));\r\n");
      out.write("    </script><script src=\" http://hm.baidu.com/h.js?467a2b45543928de4d32a9f7c3bfc175\" type=\"text/javascript\"></script><a href=\"http://tongji.baidu.com/hm-web/welcome/ico?s=467a2b45543928de4d32a9f7c3bfc175\" target=\"_blank\"><img border=\"0\" src=\"http://eiv.baidu.com/hmt/icon/21.gif\" width=\"20\" height=\"20\"></a>\r\n");
      out.write("    <!-- 百度推广JS END -->\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("</body></html>");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005foverride_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:override
    tags.OverrideTag _jspx_th_layout_005foverride_005f0 = (tags.OverrideTag) _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname.get(tags.OverrideTag.class);
    _jspx_th_layout_005foverride_005f0.setPageContext(_jspx_page_context);
    _jspx_th_layout_005foverride_005f0.setParent(null);
    // /jsp/homepage/admin_register.jsp(3,0) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_layout_005foverride_005f0.setName("main_content");
    int _jspx_eval_layout_005foverride_005f0 = _jspx_th_layout_005foverride_005f0.doStartTag();
    if (_jspx_eval_layout_005foverride_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_layout_005foverride_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_layout_005foverride_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_layout_005foverride_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("\t<br />\r\n");
        out.write("\r\n");
        out.write("\t<form class=\"form-inline\" action=\"student_register\" method=\"POST\"\r\n");
        out.write("\t\tid=\"admin_register_form\">\r\n");
        out.write("\r\n");
        out.write("\t\t<div class=\"alert alert-info\" role=\"alert\" id=\"alert_register_info\"\r\n");
        out.write("\t\tstyle=\"display: none\">\r\n");
        out.write("\t\t<br />\r\n");
        out.write("\t</div>\r\n");
        out.write("\t\t<div class=\"form-group col-lg-offset-4\">\r\n");
        out.write("\t\t\t<label for=\"username\">用&nbsp;&nbsp;户&nbsp;&nbsp;名</label> <input type=\"text\"\r\n");
        out.write("\t\t\t\tclass=\"form-control\" name=\"username\" id=\"usernameId\"\r\n");
        out.write("\t\t\t\tonblur=checkUsername() value=\"");
        if (_jspx_meth_s_005fproperty_005f0(_jspx_th_layout_005foverride_005f0, _jspx_page_context))
          return true;
        out.write("\"\r\n");
        out.write("\t\t\t\tplaceholder=\"用作登录的用户名\">\r\n");
        out.write("\t\t</div>\r\n");
        out.write("\r\n");
        out.write("\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t<span style=\"color: red\" id=username_msg>*</span>\r\n");
        out.write("\t\t</div>\r\n");
        out.write("\t\t  <br><br>\r\n");
        out.write("\t\t  \r\n");
        out.write("\t\t<div class=\"form-group col-lg-offset-4\">\r\n");
        out.write("\t\t\t<label for=\"password\">密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>\r\n");
        out.write("\t\t\t<input type=\"password\" class=\"form-control\" name=\"password\"\r\n");
        out.write("\t\t\t\tonblur=checkPassword() id=\"passwordId\"\r\n");
        out.write("\t\t\t\tvalue=\"");
        if (_jspx_meth_s_005fproperty_005f1(_jspx_th_layout_005foverride_005f0, _jspx_page_context))
          return true;
        out.write("\" placeholder=\"\">\r\n");
        out.write("\t\t</div>\r\n");
        out.write("\t\t\r\n");
        out.write("\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t<span style=\"color: red\" id=password_msg>*</span>\r\n");
        out.write("\t\t</div>\r\n");
        out.write("  <br><br>\r\n");
        out.write("\r\n");
        out.write("\t\t\r\n");
        out.write("\t\t<div class=\"form-group col-lg-offset-4\">\r\n");
        out.write("\t\t\t<label for=\"passwordAgain\">确认密码</label> <input type=\"password\"\r\n");
        out.write("\t\t\t\tclass=\"form-control\" name=\"passwordAgain\" id=\"passwordAgainId\"\r\n");
        out.write("\t\t\t\tonblur=checkPasswordAgain() value=\"");
        if (_jspx_meth_s_005fproperty_005f2(_jspx_th_layout_005foverride_005f0, _jspx_page_context))
          return true;
        out.write("\"\r\n");
        out.write("\t\t\t\tplaceholder=\"\">\r\n");
        out.write("\t\t</div>\r\n");
        out.write("\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t<span style=\"color: red\" id=passwordAgain_msg>*</span>\r\n");
        out.write("\t\t</div>\r\n");
        out.write("\t\t  <br><br>\r\n");
        out.write("\t\t<div class=\"form-group col-lg-offset-4\">\r\n");
        out.write("\t\t\t<label for=\"fullName\">姓&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;名</label>\r\n");
        out.write("\t\t\t<input type=\"text\" class=\"form-control\" name=\"fullName\" id=\"fullName\"\r\n");
        out.write("\t\t\t\tvalue=\"");
        if (_jspx_meth_s_005fproperty_005f3(_jspx_th_layout_005foverride_005f0, _jspx_page_context))
          return true;
        out.write("\" placeholder=\"\">\r\n");
        out.write("\t\t</div>\r\n");
        out.write("\t\t<br> <br> \r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\t\t");
        out.write("\r\n");
        out.write("\t\t\r\n");
        out.write("\t\t <div class=\"form-group col-lg-offset-4\">\r\n");
        out.write("\t  \t<label for=\"sex\">性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别</label>\r\n");
        out.write("\t  \t");
        if (_jspx_meth_s_005fselect_005f0(_jspx_th_layout_005foverride_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t  </div>   \r\n");
        out.write("  \t<br><br>\r\n");
        out.write("\t\t<div class=\"form-group col-lg-offset-4\">\r\n");
        out.write("\t\t\t\r\n");
        out.write("\t\t\t<label for=\"profilePhotoPath\">上传头像</label> \r\n");
        out.write("\t\t\t <input type=\"file\" class =\"pull-right \"name=\"profilePhotoPath\" id=\"file_upload\"  placeholder=\"图片地址\"> \r\n");
        out.write("\t\t\t\r\n");
        out.write("\t\t\t <br>\r\n");
        out.write("\t\t\t ");
        if (_jspx_meth_s_005ffielderror_005f0(_jspx_th_layout_005foverride_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t ");
        out.write("\r\n");
        out.write("\t\t</div>\r\n");
        out.write("\t\t\r\n");
        out.write("\t\t<br> <br> \r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\t\t<div class=\"form-group col-lg-offset-4\">\r\n");
        out.write("\t\t\t<label for=\"unitInfo\">工作单位</label> <input type=\"text\"\r\n");
        out.write("\t\t\t\tclass=\"form-control\" name=\"unitInfo\" id=\"unitInfo\"\r\n");
        out.write("\t\t\t\tvalue=\"");
        if (_jspx_meth_s_005fproperty_005f4(_jspx_th_layout_005foverride_005f0, _jspx_page_context))
          return true;
        out.write("\" placeholder=\"\">\r\n");
        out.write("\t\t</div>\r\n");
        out.write("  <br><br>\r\n");
        out.write("\r\n");
        out.write("\t\t<div class=\"form-group col-lg-offset-4\">\r\n");
        out.write("\t\t\t<label for=\"phoneNumber\">联系方式</label> <input type=\"text\"\r\n");
        out.write("\t\t\t\tclass=\"form-control\" name=\"phoneNumber\" id=\"phoneNumber\"\r\n");
        out.write("\t\t\t\tvalue=\"");
        if (_jspx_meth_s_005fproperty_005f5(_jspx_th_layout_005foverride_005f0, _jspx_page_context))
          return true;
        out.write("\" placeholder=\"\">\r\n");
        out.write("\t\t</div>\r\n");
        out.write("\r\n");
        out.write("\t\t<br> <br> \r\n");
        out.write("\r\n");
        out.write("\t\t<div class=\"form-group col-lg-offset-4\">\r\n");
        out.write("\t\t\t<label for=\"remark\">备&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;注</label>\r\n");
        out.write("\t\t\t<input type=\"\" text\"\" class=\"form-control\" name=\"remark\" id=\"remark\"\r\n");
        out.write("\t\t\t\tvalue=\"");
        if (_jspx_meth_s_005fproperty_005f6(_jspx_th_layout_005foverride_005f0, _jspx_page_context))
          return true;
        out.write("\" placeholder=\"\">\r\n");
        out.write("\t\t</div>\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\t\t<br /> <br />\r\n");
        out.write("\t\t<button type=\"button\" class=\"btn btn-primary col-lg-offset-5\">注册</button>\r\n");
        out.write("\t</form>\r\n");
        out.write("\t");
        if (_jspx_meth_s_005ffielderror_005f1(_jspx_th_layout_005foverride_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t<br />\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\t\r\n");
        if (_jspx_meth_s_005fdebug_005f0(_jspx_th_layout_005foverride_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\t<script>\r\n");
        out.write("\r\n");
        out.write("    $(document).on(\"click\", \"button\", function (){\r\n");
        out.write("    \t\r\n");
        out.write("    \t\r\n");
        out.write("    \tcheckUsername();\r\n");
        out.write("    \tcheckPassword();\r\n");
        out.write("    \tvar fd = new FormData();\r\n");
        out.write("        if(document.getElementById('file_upload').files.length != 0)\r\n");
        out.write("    \t\tfd.append(\"file\", document.getElementById('file_upload').files[0]);\r\n");
        out.write("        fd.append(\"username\",$(\"#usernameId\").val());\r\n");
        out.write("        fd.append(\"password\",$(\"#passwordId\").val());\r\n");
        out.write("        fd.append(\"fullName\",$(\"#fullName\").val());\r\n");
        out.write("        fd.append(\"sex\",$(\"#sex\").val());\r\n");
        out.write("        fd.append(\"unitInfo\",$(\"#unitInfo\").val());\r\n");
        out.write("        fd.append(\"phoneNumber\",$(\"#phoneNumber\").val());\r\n");
        out.write("        fd.append(\"remark\",$(\"#remark\").val());\r\n");
        out.write("        //var params = $('#admin_register_form').serialize(); //利用jquery将表单序列化\r\n");
        out.write("       \r\n");
        out.write("       \r\n");
        out.write("        $.ajax({\r\n");
        out.write("          url: 'admin_register_save',\r\n");
        out.write("          type: 'post',\r\n");
        out.write("          dataType: 'json',\r\n");
        out.write("          data: fd,\r\n");
        out.write("          async: true,  \r\n");
        out.write("          contentType: false,  //\r\n");
        out.write("          processData: false,  \r\n");
        out.write("          success: adminRegisterCallback\r\n");
        out.write("        });\r\n");
        out.write("        \r\n");
        out.write("    });\r\n");
        out.write("    \r\n");
        out.write("    function animatedShow(text)\r\n");
        out.write("    {\r\n");
        out.write("    \t//alert(text+\"animatedShow\");\r\n");
        out.write("    \t$(\"#alert_register_info\").hide();\r\n");
        out.write("\t\t$(\"#alert_register_info\").text(text);\r\n");
        out.write("\t\t$(\"#alert_register_info\").show(500);\r\n");
        out.write("    }\r\n");
        out.write("    function animatesHide(){\r\n");
        out.write("    \t$(\"#alert_register_info\").hide();\r\n");
        out.write("    }\r\n");
        out.write("    function adminRegisterCallback(data)\r\n");
        out.write("    {    \t\r\n");
        out.write("    \t//alert(data.register_status);\r\n");
        out.write("    \t\r\n");
        out.write("    \tif(data.register_status == \"0\")\r\n");
        out.write("    \t{    \t\t\r\n");
        out.write("        \t/* $(\"#user_table tr:first\").after(data.added_user_html);\r\n");
        out.write("        \t\r\n");
        out.write("        \t\r\n");
        out.write("        \tvar cnt = $(document).find(\"#user_table tr:eq(1)\");\r\n");
        out.write("        \t$(cnt).children().eq(0).text(data.username);\r\n");
        out.write("        \t$(cnt).children().eq(1).text(data.password);\r\n");
        out.write("        \tc\r\n");
        out.write("//         \talert(data.user_id);\r\n");
        out.write("        \t\r\n");
        out.write("\t\t\t\r\n");
        out.write("        \t$(cnt).attr(\"user_id\", data.user_id);\r\n");
        out.write(" */\t\t\t\r\n");
        out.write("    \t\talert(\"ok\");\r\n");
        out.write(" \t\t\tanimatesHide();\r\n");
        out.write(" \t\t\t \r\n");
        out.write(" \t\t\twindow.location.href = \"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/login\";\r\n");
        out.write("    \t}\r\n");
        out.write("    \t/* else if(data.register_status == \"1\")\r\n");
        out.write("    \t{\r\n");
        out.write("    \t\tanimatedShow(\"注册用户名或者密码为空\");\r\n");
        out.write("    \t} */\r\n");
        out.write("    \telse if(data.register_status == \"2\")\r\n");
        out.write("   \t\t{\r\n");
        out.write("    \t\tanimatedShow(\"注册用户名重复\");\r\n");
        out.write("   \t\t}\r\n");
        out.write("    \telse \r\n");
        out.write("   \t\t{\r\n");
        out.write("    \t\talert(\"error with status\" + data.status);\r\n");
        out.write("   \t\t}\r\n");
        out.write("\r\n");
        out.write("\t\t\r\n");
        out.write("    }\r\n");
        out.write("    \r\n");
        out.write("    //输入验证\r\n");
        out.write("    function checkUsername(){\r\n");
        out.write("    \tvar val = $(\"#usernameId\").val(); \r\n");
        out.write("    \t if(val==\"\")\r\n");
        out.write("    \t\t{\r\n");
        out.write("    \t\t $(\"#username_msg\").text(\"非空\");\r\n");
        out.write("    \t\t $(\"#usernameId\").focus();\r\n");
        out.write("    \t\t} \r\n");
        out.write("    \t else\r\n");
        out.write("    \t\t $(\"#username_msg\").text(\"\");\r\n");
        out.write("    }\r\n");
        out.write("    \r\n");
        out.write("    function checkPassword(){\r\n");
        out.write("    \tvar val = $(\"#passwordId\").val(); \r\n");
        out.write("   \t if(val==\"\")\r\n");
        out.write("   \t\t{\r\n");
        out.write("   \t\t $(\"#password_msg\").text(\"非空\");\r\n");
        out.write("   \t     $(\"#passwordId\").focus(); \r\n");
        out.write("   \t\t} \r\n");
        out.write("   \t else\r\n");
        out.write("   \t\t$(\"#password_msg\").text(\"\");\r\n");
        out.write("    }\r\n");
        out.write("    \r\n");
        out.write("    function checkPasswordAgain(){\r\n");
        out.write("    \tvar val = $(\"#passwordId\").val(); \r\n");
        out.write("      \tvar val2 = $(\"#passwordAgainId\").val(); \r\n");
        out.write("           \t\r\n");
        out.write("      \tif(val!=val2)\r\n");
        out.write("      \t\t{\r\n");
        out.write("      \t\t $(\"#passwordAgain_msg\").text(\"密码不一致\");\r\n");
        out.write("      \t     $(\"#passwordAgainId\").focus(); \r\n");
        out.write("      \t\t} \r\n");
        out.write("      \t else\r\n");
        out.write("      \t\t {\r\n");
        out.write("      \t\t$(\"#passwordAgain_msg\").text(\"\");\r\n");
        out.write("      \t\t }\r\n");
        out.write("    }\r\n");
        out.write("</script>\r\n");
        out.write("\r\n");
        int evalDoAfterBody = _jspx_th_layout_005foverride_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_layout_005foverride_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_layout_005foverride_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname.reuse(_jspx_th_layout_005foverride_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005flayout_005foverride_0026_005fname.reuse(_jspx_th_layout_005foverride_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_layout_005foverride_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f0 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_layout_005foverride_005f0);
    // /jsp/homepage/admin_register.jsp(16,34) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f0.setValue("username");
    int _jspx_eval_s_005fproperty_005f0 = _jspx_th_s_005fproperty_005f0.doStartTag();
    if (_jspx_th_s_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_layout_005foverride_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f1 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_layout_005foverride_005f0);
    // /jsp/homepage/admin_register.jsp(29,11) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f1.setValue("password");
    int _jspx_eval_s_005fproperty_005f1 = _jspx_th_s_005fproperty_005f1.doStartTag();
    if (_jspx_th_s_005fproperty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f1);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_layout_005foverride_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f2 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f2.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_layout_005foverride_005f0);
    // /jsp/homepage/admin_register.jsp(41,39) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f2.setValue("passwordAgain");
    int _jspx_eval_s_005fproperty_005f2 = _jspx_th_s_005fproperty_005f2.doStartTag();
    if (_jspx_th_s_005fproperty_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f2);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_layout_005foverride_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f3 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f3.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_layout_005foverride_005f0);
    // /jsp/homepage/admin_register.jsp(51,11) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f3.setValue("fullName");
    int _jspx_eval_s_005fproperty_005f3 = _jspx_th_s_005fproperty_005f3.doStartTag();
    if (_jspx_th_s_005fproperty_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f3);
    return false;
  }

  private boolean _jspx_meth_s_005fselect_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_layout_005foverride_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:select
    org.apache.struts2.views.jsp.ui.SelectTag _jspx_th_s_005fselect_005f0 = (org.apache.struts2.views.jsp.ui.SelectTag) _005fjspx_005ftagPool_005fs_005fselect_0026_005fstyle_005fname_005flist_005fid_005fclass_005fnobody.get(org.apache.struts2.views.jsp.ui.SelectTag.class);
    _jspx_th_s_005fselect_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fselect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_layout_005foverride_005f0);
    // /jsp/homepage/admin_register.jsp(64,4) name = list type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f0.setList("{'男','女'}");
    // /jsp/homepage/admin_register.jsp(64,4) name = class type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f0.setCssClass("form-control");
    // /jsp/homepage/admin_register.jsp(64,4) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f0.setId("sex");
    // /jsp/homepage/admin_register.jsp(64,4) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f0.setName("sex");
    // /jsp/homepage/admin_register.jsp(64,4) name = style type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f0.setCssStyle("width:180px");
    int _jspx_eval_s_005fselect_005f0 = _jspx_th_s_005fselect_005f0.doStartTag();
    if (_jspx_th_s_005fselect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fselect_0026_005fstyle_005fname_005flist_005fid_005fclass_005fnobody.reuse(_jspx_th_s_005fselect_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fselect_0026_005fstyle_005fname_005flist_005fid_005fclass_005fnobody.reuse(_jspx_th_s_005fselect_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005ffielderror_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_layout_005foverride_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:fielderror
    org.apache.struts2.views.jsp.ui.FieldErrorTag _jspx_th_s_005ffielderror_005f0 = (org.apache.struts2.views.jsp.ui.FieldErrorTag) _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody.get(org.apache.struts2.views.jsp.ui.FieldErrorTag.class);
    _jspx_th_s_005ffielderror_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005ffielderror_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_layout_005foverride_005f0);
    int _jspx_eval_s_005ffielderror_005f0 = _jspx_th_s_005ffielderror_005f0.doStartTag();
    if (_jspx_th_s_005ffielderror_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody.reuse(_jspx_th_s_005ffielderror_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody.reuse(_jspx_th_s_005ffielderror_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_layout_005foverride_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f4 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f4.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_layout_005foverride_005f0);
    // /jsp/homepage/admin_register.jsp(87,11) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f4.setValue("unitInfo");
    int _jspx_eval_s_005fproperty_005f4 = _jspx_th_s_005fproperty_005f4.doStartTag();
    if (_jspx_th_s_005fproperty_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f4);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_layout_005foverride_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f5 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f5.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_layout_005foverride_005f0);
    // /jsp/homepage/admin_register.jsp(94,11) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f5.setValue("phoneNumber");
    int _jspx_eval_s_005fproperty_005f5 = _jspx_th_s_005fproperty_005f5.doStartTag();
    if (_jspx_th_s_005fproperty_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f5);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_layout_005foverride_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f6 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f6.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_layout_005foverride_005f0);
    // /jsp/homepage/admin_register.jsp(102,11) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f6.setValue("remark");
    int _jspx_eval_s_005fproperty_005f6 = _jspx_th_s_005fproperty_005f6.doStartTag();
    if (_jspx_th_s_005fproperty_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f6);
    return false;
  }

  private boolean _jspx_meth_s_005ffielderror_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_layout_005foverride_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:fielderror
    org.apache.struts2.views.jsp.ui.FieldErrorTag _jspx_th_s_005ffielderror_005f1 = (org.apache.struts2.views.jsp.ui.FieldErrorTag) _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody.get(org.apache.struts2.views.jsp.ui.FieldErrorTag.class);
    _jspx_th_s_005ffielderror_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005ffielderror_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_layout_005foverride_005f0);
    int _jspx_eval_s_005ffielderror_005f1 = _jspx_th_s_005ffielderror_005f1.doStartTag();
    if (_jspx_th_s_005ffielderror_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody.reuse(_jspx_th_s_005ffielderror_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody.reuse(_jspx_th_s_005ffielderror_005f1);
    return false;
  }

  private boolean _jspx_meth_s_005fdebug_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_layout_005foverride_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:debug
    org.apache.struts2.views.jsp.ui.DebugTag _jspx_th_s_005fdebug_005f0 = (org.apache.struts2.views.jsp.ui.DebugTag) _005fjspx_005ftagPool_005fs_005fdebug_005fnobody.get(org.apache.struts2.views.jsp.ui.DebugTag.class);
    _jspx_th_s_005fdebug_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fdebug_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_layout_005foverride_005f0);
    int _jspx_eval_s_005fdebug_005f0 = _jspx_th_s_005fdebug_005f0.doStartTag();
    if (_jspx_th_s_005fdebug_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fdebug_005fnobody.reuse(_jspx_th_s_005fdebug_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fdebug_005fnobody.reuse(_jspx_th_s_005fdebug_005f0);
    return false;
  }

  private boolean _jspx_meth_layout_005fblock_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:block
    tags.BlockTag _jspx_th_layout_005fblock_005f0 = (tags.BlockTag) _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.get(tags.BlockTag.class);
    _jspx_th_layout_005fblock_005f0.setPageContext(_jspx_page_context);
    _jspx_th_layout_005fblock_005f0.setParent(null);
    // /jsp/homepage/new_home_base.jsp(113,4) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_layout_005fblock_005f0.setName("main_content");
    int _jspx_eval_layout_005fblock_005f0 = _jspx_th_layout_005fblock_005f0.doStartTag();
    if (_jspx_eval_layout_005fblock_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t");
        int evalDoAfterBody = _jspx_th_layout_005fblock_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_layout_005fblock_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005flayout_005fblock_0026_005fname.reuse(_jspx_th_layout_005fblock_005f0);
    return false;
  }
}
